- name: ensure network is in nets.boot
  lineinfile:
    path: "{{ tincvpn_config_path }}/nets.boot"
    line: "{{ tincvpn_network }}"
    create: yes

- name: Configure systemd service
  systemd:
    name: "tinc@{{ tincvpn_network }}"
    enabled: True
  when: ansible_service_mgr == 'systemd'