- name: install epel-release (redhat)
  yum:
    name: epel-release
    state: latest
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7")

- import_tasks: "install-with-snapd.yml"

- name: ensure tinc is installed
  package:
    name: tinc
    state: present
  register: package_result
  when: not tincvpn_install_with_snapd

