- block:
  - name: ensure tinc is installed
    package:
      name: snapd
      state: present
      register: package_result
  - name: enable snapd service
    service:
      name: snapd
      state: started
      enabled: yes
  - name: enable classic snap support
    file:
      src: "/var/lib/snapd/snap"
      dest: "/"
      state: symlink
  - name: Install foo
    snap:
      name: tinc-vpn
  - name: create tinc-vpn snapd configuration directory
    file:
      path: /var/snap/tinc-vpn/tinc
      state: directory
      user: root
      group: root
      mode: 0755
  - name: create tinc systemd service file for snapd
    template:
      src=tinc.service.j2
      dest=/etc/systemd/system/tinc.service
    register: tinc_service_file
  - name: systemctl daemon-reload
    shell: systemctl daemon-reload
    when: tinc_service_file.changed
  when: install_with_snapd
