- name: set custom facts for tinc VPN
  set_fact:
    tincvpn_nodename: "{{ inventory_hostname | regex_replace(tincvpn_safechars_regex, tincvpn_safechars_replacement) }}"

- import_tasks: "install.yml"
- import_tasks: "write-configuration.yml"
- import_tasks: "configure-service.yml"