#!/bin/bash

{% if route.network == 'default' and route.provider == 'scaleway' %}
# Setup the default gateway
SERVER_INTERFACE=''
while [ -z "$SERVER_INTERFACE" ]; do
SERVER_INTERFACE=`ip addr show | awk '/inet.*brd/{print $NF; exit}'`
sleep 1
done
GATEWAY=`ip route show default | awk '/default via/{print $3}'`
SERVERIP=`ifconfig ens2 | grep "inet " | awk -F'[: ]+' '{ print $3 }'`
{% endif %}

{% if 'tincvpn_'+tincvpn_network+'_ip' in hostvars[inventory_hostname] %}
ifconfig $INTERFACE {{ hostvars[inventory_hostname]['tincvpn_'+tincvpn_network+'_ip'] }} netmask {{ tincvpn_subnet|ipaddr('netmask') }}
{% endif %}


{% for route in tincvpn_routes %}
{% if route.network == 'default' %}
ip route delete default
{% if route.provider == 'scelway' %}
ip route add 10.0.0.0/8 via $GATEWAY dev $SERVER_INTERFACE
ip route add 169.254.0.0/16 via $GATEWAY dev $SERVER_INTERFACE
{% endif %}
ip route add $SERVERIP via $GATEWAY dev $SERVER_INTERFACE
{% endif %}
ip route add {{ route.network }} via {{ route.gateway }} dev $INTERFACE
{% endfor %}