#!/bin/sh

{% if 'tincvpn_'+tincvpn_network+'_ip' in hostvars[inventory_hostname] %}
ip address add dev $INTERFACE {{ hostvars[inventory_hostname]['tincvpn_'+tincvpn_network+'_ip'] }}/{{ tincvpn_subnet|ipaddr('netmask') }}
ip link set dev $INTERFACE up
{% endif %}

{% for route in tincvpn_routes %}
ip route add {{ route.network }} via {{ route.gateway }} dev $INTERFACE
{% endfor %}

{% if tincvpn_custom_up_scripts is not none and tincvpn_custom_up_scripts|length %}
{% if tincvpn_custom_up_scripts is iterable and tincvpn_custom_up_scripts is not string %}
{% for command in tincvpn_custom_up_scripts %}
{{ command }}
{% endfor %}
{% endif %}
{% endif %}
