#!/bin/sh

{% if 'tincvpn_'+tincvpn_network+'_ip' in hostvars[inventory_hostname] %}
ip address add dev $INTERFACE {{ hostvars[inventory_hostname]['tincvpn_'+tincvpn_network+'_ip'] }}/{{ tincvpn_subnet|ipaddr('netmask') }}
ip link set dev $INTERFACE up
{% endif %}

{% for route in tincvpn_routes %}
ip route add {{ route.network }} via {{ route.gateway }} dev $INTERFACE
{% endfor %}
